spring:
  application:
    name: demo.jwt
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security2
    username: springstudent
    password: springstudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # update # create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug
application:
  security:
    jwt:
      secret-key: 5890e4277d7bf7425ba83577df0fffd2a9e263fe6026f0c2d8d62fa34a131ab8 # 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
security:
  jwt:
    key: 5890e4277d7bf7425ba83577df0fffd2a9e263fe6026f0c2d8d62fa34a131ab8